name: Publish Static Web App to Azure Blob Storage

on:
  push:
    branches: [ main ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v1
    - name: Install npm packages
      shell: bash
      run: |      
        npm install
    - name: Build app
      shell: bash
      run: |      
        npm run build    
    - name: Publish app
      uses: Azure/cli@v1.0.0
      with:
        azcliversion: latest
        inlineScript: |
         az storage blob delete-batch -s "\$web" --connection-string "${{ secrets.AZ_STORAGE_CONNECTION_STRING }}"
         az storage blob upload-batch -d "\$web" -s dist --connection-string "${{ secrets.AZ_STORAGE_CONNECTION_STRING }}"
